# -*- coding: utf-8 -*-
"""Visualisasi Frekuensi Bigram dan Trigram.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VEBytFqMsQxSF1oZNdRX1VquwHnDSQM1
"""

import matplotlib.pyplot as plt


def plot_ngram_frequency(ngram_counts, ngram_type):
    ngrams = list(ngram_counts.keys())
    frequencies = list(ngram_counts.values())

    plt.bar(ngrams, frequencies)
    plt.xlabel(ngram_type)
    plt.ylabel('Frequency')
    plt.title(f'Frequency {ngram_type} in Encrypted Text')
    plt.xticks(rotation=90)
    plt.show()

# # Contoh teks terenkripsi
# encrypted_text = "JGkLnmzXJMLZnnkzkmJXZnJLXJXZZJZLZJXLLJZZZkZZkJZkJZZXJLnXJJZnZJZJLZJZLnLZJZLZJZ"

# # Menghitung frekuensi bigram
# from collections import Counter
# bigram_counts = Counter([encrypted_text[i:i+2] for i in range(len(encrypted_text)-1)])

# # Visualisasi frekuensi bigram
# plot_ngram_frequency(bigram_counts, 'Bigram')

# # Menghitung frekuensi trigram
# trigram_counts = Counter([encrypted_text[i:i+3] for i in range(len(encrypted_text)-2)])

# # Visualisasi frekuensi trigram
# plot_ngram_frequency(trigram_counts, 'Trigram')