# -*- coding: utf-8 -*-
"""Histogram Karakter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1308LiGLBb2c0W7GIMBew2gBkKmD5sece
"""

import matplotlib.pyplot as plt
from collections import Counter

def plot_histogram(text):
    # Menghitung frekuensi kemunculan karakter
    character_counts = Counter(text)
    characters = list(character_counts.keys())
    frequencies = list(character_counts.values())

    # Membuat histogram
    plt.bar(characters, frequencies)
    plt.xlabel('Character')
    plt.ylabel('Frequency')
    plt.title('Encrypted Text Character Histogram')
    plt.show()
    

# # Contoh teks terenkripsi
# encrypted_text = "JGkLnmzXJMLZnnkzkmJXZnJLXJXZZJZLZJXLLJZZZkZZkJZkJZZXJLnXJJZnZJZJLZJZLnLZJZLZJZ"

# # Memanggil fungsi plot_histogram
# plot_histogram(encrypted_text)